/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppUploadRouteImport } from './routes/_app.upload'
import { Route as AppTrendsRouteImport } from './routes/_app.trends'
import { Route as AppSystemRouteImport } from './routes/_app.system'
import { Route as AppStepsRouteImport } from './routes/_app.steps'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppProcessRouteImport } from './routes/_app.process'
import { Route as AppPredictiveRouteImport } from './routes/_app.predictive'
import { Route as AppOverlayRouteImport } from './routes/_app.overlay'
import { Route as AppDefectsRouteImport } from './routes/_app.defects'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUploadRoute = AppUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AppRoute,
} as any)
const AppTrendsRoute = AppTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemRoute = AppSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AppRoute,
} as any)
const AppStepsRoute = AppStepsRouteImport.update({
  id: '/steps',
  path: '/steps',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProcessRoute = AppProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => AppRoute,
} as any)
const AppPredictiveRoute = AppPredictiveRouteImport.update({
  id: '/predictive',
  path: '/predictive',
  getParentRoute: () => AppRoute,
} as any)
const AppOverlayRoute = AppOverlayRouteImport.update({
  id: '/overlay',
  path: '/overlay',
  getParentRoute: () => AppRoute,
} as any)
const AppDefectsRoute = AppDefectsRouteImport.update({
  id: '/defects',
  path: '/defects',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/defects': typeof AppDefectsRoute
  '/overlay': typeof AppOverlayRoute
  '/predictive': typeof AppPredictiveRoute
  '/process': typeof AppProcessRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/steps': typeof AppStepsRoute
  '/system': typeof AppSystemRoute
  '/trends': typeof AppTrendsRoute
  '/upload': typeof AppUploadRoute
}
export interface FileRoutesByTo {
  '/defects': typeof AppDefectsRoute
  '/overlay': typeof AppOverlayRoute
  '/predictive': typeof AppPredictiveRoute
  '/process': typeof AppProcessRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/steps': typeof AppStepsRoute
  '/system': typeof AppSystemRoute
  '/trends': typeof AppTrendsRoute
  '/upload': typeof AppUploadRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/defects': typeof AppDefectsRoute
  '/_app/overlay': typeof AppOverlayRoute
  '/_app/predictive': typeof AppPredictiveRoute
  '/_app/process': typeof AppProcessRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/steps': typeof AppStepsRoute
  '/_app/system': typeof AppSystemRoute
  '/_app/trends': typeof AppTrendsRoute
  '/_app/upload': typeof AppUploadRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/defects'
    | '/overlay'
    | '/predictive'
    | '/process'
    | '/reports'
    | '/settings'
    | '/steps'
    | '/system'
    | '/trends'
    | '/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/defects'
    | '/overlay'
    | '/predictive'
    | '/process'
    | '/reports'
    | '/settings'
    | '/steps'
    | '/system'
    | '/trends'
    | '/upload'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/defects'
    | '/_app/overlay'
    | '/_app/predictive'
    | '/_app/process'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/steps'
    | '/_app/system'
    | '/_app/trends'
    | '/_app/upload'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/upload': {
      id: '/_app/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AppUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trends': {
      id: '/_app/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof AppTrendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system': {
      id: '/_app/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof AppSystemRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/steps': {
      id: '/_app/steps'
      path: '/steps'
      fullPath: '/steps'
      preLoaderRoute: typeof AppStepsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/process': {
      id: '/_app/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof AppProcessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/predictive': {
      id: '/_app/predictive'
      path: '/predictive'
      fullPath: '/predictive'
      preLoaderRoute: typeof AppPredictiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/overlay': {
      id: '/_app/overlay'
      path: '/overlay'
      fullPath: '/overlay'
      preLoaderRoute: typeof AppOverlayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/defects': {
      id: '/_app/defects'
      path: '/defects'
      fullPath: '/defects'
      preLoaderRoute: typeof AppDefectsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDefectsRoute: typeof AppDefectsRoute
  AppOverlayRoute: typeof AppOverlayRoute
  AppPredictiveRoute: typeof AppPredictiveRoute
  AppProcessRoute: typeof AppProcessRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStepsRoute: typeof AppStepsRoute
  AppSystemRoute: typeof AppSystemRoute
  AppTrendsRoute: typeof AppTrendsRoute
  AppUploadRoute: typeof AppUploadRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDefectsRoute: AppDefectsRoute,
  AppOverlayRoute: AppOverlayRoute,
  AppPredictiveRoute: AppPredictiveRoute,
  AppProcessRoute: AppProcessRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStepsRoute: AppStepsRoute,
  AppSystemRoute: AppSystemRoute,
  AppTrendsRoute: AppTrendsRoute,
  AppUploadRoute: AppUploadRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
